### ISSUE TITLE
D4RK3 54B3R's flare sequencer script

### ISSUE THREAD

**Issue by MistaLemur** [TheLastBastion/se-scripts#2]
I added a new script to the suggested scripts folder.

I wrote this script for controlling and sequencing flares on combat vehicles.
In my tests thus far, this script has almost no impact on sim speed performance.
However that could change on different machines or servers, so I'd like to get additional testing in.

**Comment by CodyJamesCasey** [comment]
@MistaLemur 
code looks fine to me. Looks like it's pretty much tied to the timer block, right? So if the timer block is set reasonably, this looks pretty good!

**Comment by rwicklin** [comment]
Looks good. I think it's tied to the flares per second setting in that first block less than the timer block @CodyJamesCasey. Is that more or less accurate @MistaLemur?

And yeah so long as people set it responsibly it doesn't seem like it'd be a problem.

**Comment by MistaLemur** [comment]
Rwicklin is correct. Timer block must be set to trigger itself, so the script runs at 60Hz. It does not have anything to do with the timer delay seeing. However it only does anything if the user is trying to launch flares, and only ever at the flare launching rate.

Again in my testing I am unable to observe any drop in Sim speed when running this.

**Comment by MistaLemur** [comment]
Since both of you guys are OK with this, I'll mark this as approved and move it into the approved folder
