### ISSUE TITLE
Kankub's miner script

### ISSUE THREAD

**Issue by MistaLemur** [TheLastBastion/se-scripts#3]
I added a new script to the suggested scripts folder.

It's a script for displaying cargo capacity on the ship; it doesn't really do much else.
If approved, it should be run with a timer with >1 second delay.

**Comment by CodyJamesCasey** [comment]
@MistaLemur  LGTM

**Comment by rwicklin** [comment]
Ditto, this seems fine m8

**Comment by MistaLemur** [comment]
Adding to approved
