### ISSUE TITLE
D4RK3 54B3R's SAM Site script

### ISSUE THREAD

**Issue by MistaLemur** [TheLastBastion/se-scripts#4]
Hey guys, I wrote a new script and added it to the suggested scripts folder.

It essentially uses a target painter turret alongside guided missile launchers to automatically launch missiles at nearby enemies if the target painter sees anything.

It runs off of a timer block, generally at either 3 second delay or 1 second delay depending on if there are enemies present. Each run, though, it does very very very little computation, so it should have a very light CPU load.

It essentially allows you to use guided missiles as a passive defense, kind of like putting up other turrets normally for defense. 

Look through it and let me know what you think :)

**Comment by MistaLemur** [comment]
Later on, I may update this to use laser antennas to signal an alert at remote grids. But I don't think that's really going to be a think for a while, if ever at all.

**Comment by CodyJamesCasey** [comment]
@MistaLemur LGTM 👍

**Comment by MistaLemur** [comment]
Script is obsolete.
